server:
  port: 9999 # Using random port

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: # discovery server url
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: mohang-member-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100


logging:
  level:
    root: info
    org.hiberante.SQL: debug
    org.hiberante.type: debug
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기